############################################################
#
# web?????  ???8088
#
############################################################
server:
  port: 8088
  tomcat:
    uri-encoding: utf-8
  max-http-header-size: 80KB
  servlet:
    context-path: /dota


############################################################
#
# ???????
#
############################################################
spring:
  datasource: # ????????
    type: com.zaxxer.hikari.HikariDataSource # ??????HikariCP
    driver-class-name: com.mysql.jdbc.Driver # mysql??
    url: jdbc:mysql://localhost:3306/dota?useUnicode=true&characterEncoding=UTF-8&autoReconnect&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: 123456
    hikari:
      connection-timeout: 30000 # ???????????????????????????????????SQ
      minimum-idle: 5 # ?????
      maximum-pool-size: 20 # ?????
      auto-commit: true # ????
      idle-timeout: 600000 # ?????????????????????retired????:10??
      pool-name: DateSourceHikariCP # ?????
      max-lifetime: 1800000 # ?????????????????????????retired????:30??
      connection-test-query: SELECT 1
  redis:
    # Redis????
    host: 127.0.0.1
    port: 6379
    #    password: huanghao666
    database: 0
  servlet:
    multipart:
      max-file-size: 512000  # ?????????500kb
      max-request-size: 512000 # ???????500kb
  session:
    store-type: redis

############################################################
#
# mybatis ??
#
############################################################
mybatis:
  type-aliases-package: com.hh.pojo # ??POJO??????
  mapper-locations: classpath:mapper/*.xml # mapper????
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl


############################################################
#
# mybatis mapper ??
#
############################################################
# ?? Mapper ??
mapper:
  mappers: com.hh.my.mapper.MyMapper
  not-empty: false    # username != null, ???? username != ''
  identity: MYSQL
# ??????
pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true

